# Generated by Django 4.2 on 2023-04-14 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('options', '0001_initial'),
        ('tweets', '0007_remove_tweet_tweet_id_alter_tweet_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('source', models.URLField()),
                ('rating', models.CharField(choices=[('F', 'F'), ('O', 'O'), ('M', 'M'), ('X', 'X')], default='F', max_length=8)),
                ('queue', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='options.blog')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='options.tag')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='tweets.tweet')),
            ],
        ),
    ]
