# Generated by Django 4.2 on 2023-04-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nt_post_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
