# Generated by Django 4.2 on 2023-04-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_rename_posted_tweet_tweeted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
