# Generated by Django 4.2 on 2023-04-12 19:19

from django.db import IntegrityError, migrations, models, transaction


class BreakTweetTid:
    def create(apps, schema_editor):
        db_alias = schema_editor.connection.alias
        Tweet = apps.get_model('tweets', 'Tweet')
        for tweet in Tweet.objects.using(db_alias).all():
            with transaction.atomic():
                tid = tweet.tid
                author, _, status_id = str(tid).split("/")
                tweet.author = author
                tweet.status_id = status_id
                tweet.save()

    def revert(apps, schema_editor):
        db_alias = schema_editor.connection.alias
        Tweet = apps.get_model('tweets', 'Tweet')
        for tweet in Tweet.objects.using(db_alias).all():
            tweet.tid = f"{tweet.author}/status/{tweet.status_id}"
            tweet.save()


class Migration(migrations.Migration):
    dependencies = [
        ('tweets', '0004_alter_tweetimage_options_tweetimage_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['tweeted']},
        ),
        migrations.AddField(
            model_name='tweet',
            name='author',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AddField(
            model_name='tweet',
            name='status_id',
            field=models.CharField(default='b', max_length=50),
        ),
        migrations.RunPython(BreakTweetTid.create, reverse_code=BreakTweetTid.revert),
        migrations.RemoveField(
            model_name='tweet',
            name='tid',
        ),
    ]
