# Generated by Django 4.2 on 2023-04-13 14:09
from django.db import migrations, models, transaction


class SetTweetId:
    def set_id(apps, schema_editor):
        db_alias = schema_editor.connection.alias
        Tweet = apps.get_model('tweets', 'Tweet')
        TweetImage = apps.get_model('tweets', 'TweetImage')
        for image in TweetImage.objects.using(db_alias).select_related('tweet').all():
            with transaction.atomic():
                tweet = Tweet.objects.using(db_alias).get(pk=image.tweet.pk)
                tweet_id = tweet.tweet_id
                tweet.id = tweet_id
                tweet.save()

                image.tweet = tweet
                image.save()

    def revert(apps, schema_editor):
        db_alias = schema_editor.connection.alias
        Tweet = apps.get_model('tweets', 'Tweet')
        for tweet in Tweet.objects.using(db_alias).all():
            tweet_id = tweet.id
            tweet.tweet_id = tweet_id
            tweet.save()


class Migration(migrations.Migration):
    dependencies = [
        ('tweets', '0006_rename_status_id_tweet_tweet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.RunPython(SetTweetId.set_id, reverse_code=SetTweetId.revert),
        migrations.RemoveField(
            model_name='tweet',
            name='tweet_id',
        ),
    ]
