# Generated by Django 4.2 on 2023-04-14 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('tweets', '0007_remove_tweet_tweet_id_alter_tweet_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetimage',
            name='is_posted',
        ),
        migrations.AddField(
            model_name='tweetimage',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='tweetimage',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tweets.tweet'),
        ),
    ]
