# Generated by Django 4.2 on 2024-12-04 17:46

import mimetypes
import os

import requests
from django.core.files.base import ContentFile
from django.db import migrations, models

import tweets.models


def fetch_and_save_images(apps, schema_editor):
    def fetch_image(url):
        response = requests.get(url, timeout=10)
        response.raise_for_status()
        # Extract file extension from Content-Type header
        content_type = response.headers.get("Content-Type")
        extension = mimetypes.guess_extension(content_type) or ".jpg"  # Default to .jpg if unknown
        file_name = os.path.splitext(os.path.basename(url))[0] + extension
        return file_name, response.content

    TweetImage = apps.get_model("tweets", "TweetImage")
    for tweet_image in TweetImage.objects.all():
        # Process thumbnail
        if tweet_image.thumb:
            try:
                file_name, content = fetch_image(tweet_image.thumb)
                tweet_image.thumbnail.save(file_name, ContentFile(content), save=False)
            except Exception as e:
                print(f"Failed to fetch thumbnail for {tweet_image.id}: {e}")
        # Process large image
        if tweet_image.large:
            try:
                file_name, content = fetch_image(tweet_image.large)
                tweet_image.large_image.save(file_name, ContentFile(content), save=False)
            except Exception as e:
                print(f"Failed to fetch large image for {tweet_image.id}: {e}")
        # Save the instance after setting fields
        tweet_image.save()


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0010_tweet_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweetimage",
            name="large_image",
            field=models.ImageField(upload_to=tweets.models.large_image_path, null=True),
        ),
        migrations.AddField(
            model_name="tweetimage",
            name="thumbnail",
            field=models.ImageField(upload_to=tweets.models.thumbnail_path, null=True),
        ),
        migrations.RunPython(fetch_and_save_images),
        migrations.RemoveField(
            model_name="tweetimage",
            name="large",
        ),
        migrations.RemoveField(
            model_name="tweetimage",
            name="thumb",
        ),
    ]
